apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hello-inference-kv
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.serviceAccount.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: langfuse-public-key
          objectType: secret
        - |
          objectName: langfuse-secret-key
          objectType: secret
  secretObjects:
    - secretName: hello-inference-secrets
      type: Opaque
      data:
        - objectName: langfuse-public-key
          key: LANGFUSE_PUBLIC_KEY
        - objectName: langfuse-secret-key
          key: LANGFUSE_SECRET_KEY
